### ISSUE TITLE
Echidna publish not happy with 2023/software-license

### ISSUE THREAD

**Issue by inexorabletash** [speced/bikeshed-boilerplate#44]
Failure: https://github.com/w3c/IndexedDB/actions/runs/5259462159/jobs/9505063522
```
Specberus Errors:
The link for text 'permissive document license' is expected to be 'https://www.w3.org/Consortium/Legal/copyright-software' or 'https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document', but found 'https://www.w3.org/Consortium/Legal/2023/software-license' in document.
...
💥 Echidna publish has failed.
```

Looks like this comes from https://github.com/speced/bikeshed-boilerplate/blob/main/boilerplate/w3c/copyright.include and https://github.com/speced/bikeshed-boilerplate/pull/42/files made the change

**Comment by jyasskin** [comment]
It looks like @deniak is the right person to ping for https://github.com/w3c/specberus issues.

**Comment by inexorabletash** [comment]
Also FYI, Echidna eventually sent mail suggesting an issue could be filed against https://github.com/w3c/echidna/issues  citing: Found while trying to publish “echidna.tar” (see the [publication job](https://labs.w3.org/echidna/api/status?id=ba0e3af8-7c64-4d1e-bdc0-0e35ee60da10)).

**Comment by tabatkins** [comment]
Lolllll, the first recommended URL *redirects* to the URL it's complaining about. That's definitely an Echidna issue, then; I'll file it.

**Comment by tabatkins** [comment]
Rather, it's a Specberus issue, because it does accept a dated link, just the old one.

In the meantime, I've updated the boilerplate to use the undated link, and just kicked off an update to the data files, so a `bikeshed update` should fix things up for y'all in a few minutes.

**Comment by inexorabletash** [comment]
... and a rerun gives a green check. Thanks @tabatkins !
